Ohayo/Ohayo/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views
urlpatterns = [
    path('',views.main),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls'))
]

Ohayo/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('my_movie/',views.my_movie,name='my_movie'),
    path('my_movie/<int:movie_pk>/delete/',views.my_movie_delete,name='my_movies_delete'),
]

Ohayo/movies/urls.py
from django.urls import path
from . import views

app_name ='movies'

urlpatterns = [
    path('',views.index, name='index'),
    path('main', views.main, name='main'),
    path('select/', views.select, name='select'),
    path('clear/', views.clear, name='clear'),
    # path('show_movies/',views.show_movies,name='show_movies'),
    path('<int:keyword_pk>/like/',views.like_keyword,name='like_keyword'),
    path('<int:movie_pk>/movie_like/',views.like_movie,name='like_movie'),
    path('content/', views.content, name='content'),
    
]

Ohayo/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pass

Ohayo/movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Keyword(models.Model) :
    name=models.CharField(max_length=30)
    key_image=models.TextField()
    like_users=models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='like_keywords')
class Movie(models.Model):
    title=models.TextField()
    #user 의 N개의 post
    baged_users=models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='bagging_movies', blank=True)
    keywords=models.ManyToManyField(Keyword,blank=True, related_name='movies')
    code=models.TextField()
    imageUrl=models.TextField()
    is_like=models.TextField(blank=True,default=False)
    @property
    def like_count(self) :
        return self.baged_users.count()
        
class Image(models.Model) :
    mv_key_img = models.TextField()
    movie=models.ForeignKey(Movie,on_delete=models.CASCADE)

Ohayo/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username']
        help_text = {'username': ''}

Ohayo/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from .forms import UserCustomCreationForm
# Create your views here.

def signup(request):
    if request.method == "POST":
        signup_form = UserCustomCreationForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            auth_login(request,user)
            return redirect('accounts:login')
    else:
        signup_form = UserCustomCreationForm()
    context = {'signup_form': signup_form}
    return render(request, 'accounts/signup2.html', context)

def login(request):
    if request.method == "POST":
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('movies:main')
    else:
        login_form = AuthenticationForm()
    context = {'login_form': login_form}
    return render(request, 'accounts/login2.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:main')
    
@login_required
def my_movie(request) :
    User=request.user
    my_movies=User.bagging_movies.all()
    return render(request,'accounts/my_movie.html',{'my_movies':my_movies})
    
@login_required
def my_movie_delete(request,movie_pk) :
    User=request.user
    movie=User.bagging_movies.get(pk=movie_pk)
    movie.delete()
    return redirect('accounts:my_movie')

Ohayo/movies/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Keyword,Movie
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
import requests, pprint
# Create your views here.

def index(request) :
    keywords=Keyword.objects.all()
    movies=Movie.objects.all()
    if request.user.is_authenticated :
        user=request.user
        if user.like_keywords.all() :
            return redirect('movies:content')
    context={
        'keywords':keywords,
        'movies':movies
    }
    return render(request,'movies/index.html',context)
    
def main(request):
    return render(request, 'movies/main.html')
    
# def show_movies(request) :
#     user=request.user
#     movies=Movie.objects.all()
#     movie_list=[]
#     if user.like_keywords.all() :
#         for user_keyword in user.like_keywords.all() :
#             for movies in user_keyword.movies.all() :
#                 if movies not in movie_list :
#                     movie_list.append(movies)
#         print(movie_list)
#         return render(request,'movies/show_movies.html',{'user_keywords':user.like_keywords.all(),'movies':movie_list})
#     else :
#         return redirect('movies:index')

def like_keyword(request,keyword_pk) :
    keyword=get_object_or_404(Keyword,pk=keyword_pk)
    user=request.user
    print(keyword)
    print(user)
    if keyword not in user.like_keywords.all() :
        user.like_keywords.add(keyword)
        is_like=True
        
    else :
        user.like_keywords.remove(keyword)
        is_like=False
    return JsonResponse({'is_like':is_like})
    
def select(request):
    keywords = Keyword.objects.all()
    context = {'keywords': keywords}
    return render(request, 'movies/select.html', context)
    
def clear(request):
    request.user.like_keywords.clear()
    return redirect('movies:index')

@login_required
def like_movie(request,movie_pk) :
    movie=get_object_or_404(Movie,pk=movie_pk)
    user=request.user
    if user in movie.baged_users.all():
        movie.baged_users.remove(user)
        movie.is_like = False
        movie.save()
        
    else :
        movie.baged_users.add(user)
        movie.is_like = True
        movie.save()
    return JsonResponse({})
    
def content(request):
    user=request.user
    movies=Movie.objects.all()
    movie_list=[]
    if user.like_keywords.all() :
        for user_keyword in user.like_keywords.all() :
            for movies in user_keyword.movies.all() :
                if movies not in movie_list :
                    movie_list.append(movies)
        print(movie_list)
        return render(request,'movies/content.html',{'user_keywords':user.like_keywords.all(),'movies':movie_list})
    else :
        return redirect('movies:index')

Ohayo/Ohayo/templates/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" id="defaultbar">
  <a class="navbar-brand" href="{% url 'movies:content' %}"><img src="{% static 'movies/images/maneki-neko.png' %}" style="width: 30px; height: 30px;"> | Ohayo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'movies:main' %}">메인으로<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'movies:clear' %}">키워드 다시선택<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:my_movie' %}">담아둔 영화 목록<span class="sr-only">(current)</span></a>
      </li>
    </ul>
    {% if request.user.is_authenticated %}
<div class="dropleft">
  <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    {{ request.user }}
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{% url 'accounts:logout' %}">로그아웃</a>
  </div>
</div>
    {% else %}
<div class="dropleft">
  <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    GUEST
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="">회원가입</a>
    <a class="dropdown-item" href="">로그인</a>
  </div>
</div>
    {% endif %}
  </div>
</nav>

Ohayo/Ohayo/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Jua" rel="stylesheet">
    {% block css %}{% endblock %}
</head>

<body>
    {% include '_navbar.html' %}
    {% block body %} {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    {% block script %} {% endblock %}
</body>

</html>

Ohayo/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<div class="container">
<form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <input type="submit" value="로그인">
</form>
</div>
{% endblock %}

Ohayo/accounts/templates/accounts/login2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>
    {% load static %}
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'signup/fonts/material-icon/css/material-design-iconic-font.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Yeon+Sung" rel="stylesheet">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'signup/css/signup_style.css' %}">
    <link rel="stylesheet" href="{% static 'signup/css/form_style.css' %}">
</head>
<body>
    {% load static %}
    {% load crispy_forms_tags %}
    <div class="main">

        <section class="signup">
            <!-- <img src="images/signup-bg.jpg" alt=""> -->
            <div class="container" style="text-align: center;">
                <div class="signup-content">
                    <form method="POST">
                        <h2 class="form-title">Login</h2>
                        {% csrf_token %}
                        {{ login_form|crispy }}
                        <input type="submit" value="로그인" style="font-family: 'Yeon Sung', cursive; font-size: large;">
                    </form>
                    <p class="loginhere">
                        계정이 없으신가요? <a href="{% url 'accounts:signup' %}" class="loginhere-link">Login here</a>
                    </p>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="{% static 'signup/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'signup/js/login_main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

Ohayo/accounts/templates/accounts/my_movie.html
{% extends 'base.html' %}

{% block body %}
<h3 class="my-5" style="text-align: center; font-family: 'Jua', sans-serif;">{{ user }}님이 담은 영화</h3>

<ul class="nav justify-content-center">
    {% for movie in my_movies %}
    <li class="nav-item">
        <a class="nav-link active" href="#{{ movie.pk }}"><img src="{{ movie.imageUrl }}" style="width: 180px; height:360px;"></a>
        <p class="text-center">{{ movie.title }}</p>
    </li>
    {% endfor %}
</ul>
{% endblock %}

Ohayo/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block body %}
{% load crispy_forms_tags %}
<div class="container">
<form method='POST'>
    {% csrf_token %}
    {{ signup_form|crispy }}
    <input type="submit" value="회원가입">
</form>
</div>
{% endblock %}

Ohayo/accounts/templates/accounts/signup2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>
    {% load static %}
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'signup/fonts/material-icon/css/material-design-iconic-font.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Yeon+Sung" rel="stylesheet">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'signup/css/signup_style.css' %}">
    <link rel="stylesheet" href="{% static 'signup/css/form_style.css' %}">
</head>
<body>
    {% load static %}
    {% load crispy_forms_tags %}
    <div class="main">

        <section class="signup">
            <!-- <img src="images/signup-bg.jpg" alt=""> -->
            <div class="container" style="text-align: center;">
                <div class="signup-content">
                    <form method="POST" id="signup-form" class="signup-form">
                        <h2 class="form-title">Login</h2>
                        {% csrf_token %}
                        {{ signup_form|crispy }}
                        <input type="submit" value="회원가입" style="font-family: 'Yeon Sung', cursive; font-size: large;">
                    </form>
                    <p class="loginhere">
                        이미 계정이 있으신가요? <a href="{% url 'accounts:login' %}" class="loginhere-link">Login here</a>
                    </p>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="{% static 'signup/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'signup/js/login_main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

Ohayo/movies/templates/movies/index.html
{% extends 'base.html' %}
{% load static %} {% block title %}{% endblock %} {% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'movies/stylesheets/select.css' %}" />{% load static %}
<!-- Font Icon -->
<link rel="stylesheet" href="{% static 'signup/fonts/material-icon/css/material-design-iconic-font.min.css' %}">
<link href="https://fonts.googleapis.com/css?family=Yeon+Sung" rel="stylesheet">

<!-- Main css -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'signup/css/index.css' %}">
<link rel="stylesheet" href="{% static 'signup/css/button.css' %}">
<link rel="stylesheet" href="{% static 'signup/css/form_style.css' %}"> {% endblock %} {% block body %}
    {% load static %}
    <img class="centerBanner" src="" onerror="this.src='{% static 'movies/images/DJ1.jpg' %}'" style="height:400px; width:400px;"></img>
    <!--onerror="this.src='/test/noImg.gif'-->
    <div class="container">
        <ul class="ks-cboxtags">
            {% for keyword in keywords %}
            <li><input type="checkbox" id="{{ keyword.pk }}" data-id="{{ keyword.pk }}" class="click-like" value="{{ keyword.name }}">
                <label for="{{ keyword.pk }}" class="hoverImg" data-img="{{ keyword.key_image }}">{{ keyword.name }}</label>
            </li>
            {% endfor %}
        </ul>
        
    </div>
    <a href="{% url 'movies:content' %}" class="d-flex rainbow rainbow-1 justify-content-center align-items-center" style="color: black; text-decoration:none; width: 200px; height: 200px;"><i class="far fa-paper-plane fa-7x"></i><a/>
{% endblock %} {% block script %}
<script>
    let clickLikes = document.querySelectorAll('.click-like')

    clickLikes.forEach(function(clicklike) {
        clicklike.addEventListener('click', function(e) {
            const keywordId = e.target.dataset.id
            console.log(keywordId)
            axios.get(`/movies/${keywordId}/like/`).then(function(res) {
                console.log(res.data.is_like)
                // if (res.data.is_like){
                // e.target.classList.remove('far')
                // e.target.classList.add('fas')
                //     }
                // else {
                // e.target.classList.remove('fas')
                // e.target.classList.add('far')
                //     }
            })
        })
    })
    var imgs = document.querySelectorAll('.hoverImg')
    // console.log(img)
    imgs.forEach(function(img){
    img.addEventListener('mouseover', function(e) {
        console.log(e.target.dataset.img)
        image = e.target.dataset.img
        let srctag = document.querySelector('.centerBanner')
        console.log(srctag)
        srctag.src = image
        // srctag.addEventListener('mouseout', function(e){
        //     srctag.src = ''
        // })
        })
    })




    // let imgs = document.querySelectorAll('#centerBanner')
    // imgs.forEach(function(img){
    //     img.addEventListener('mouseover',function(e){
    //         console.log(e.target.dataset.id)  
    //         })
    // })
</script>
{% endblock %}

Ohayo/movies/templates/movies/main.html
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
		<meta name="viewport" content="width=device-width, initial-scale=1"> 
		<title>Hover Effect Ideas | Set 2</title>
		<meta name="description" content="Hover Effect Ideas: Inspiration for subtle hover effects" />
		<meta name="keywords" content="hover effect, inspiration, grid, thumbnail, transition, subtle, web design" />
		<meta name="author" content="Codrops" />
		{% load static %}
		<link rel="shortcut icon" href="../favicon.ico">
		<link href='http://fonts.googleapis.com/css?family=Raleway:400,800,500,600' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="{% static 'movies/stylesheets/main.css' %}" />
	</head>
	<body>
	    {% load static %}
			<div class="content">
				<div class="grid">
					<figure class="effect-apollo">
						<img src="{% static 'movies/images/background.jpg' %}"/>
						<figcaption>
							<h1>대전 1반 <span style="margin-left: 20px;">Ohayo</span></h1>
							{% if user.is_authenticated %}
							<h2><p class="n1"><a style="color:white; text-decoration:none" href="{% url 'movies:index' %}">영화 고르기</a></p></h2>
							<h2><p class="n2"><a style="color:white; text-decoration:none" href="{% url 'accounts:logout' %}">로그아웃</a></p></h2>
							{% else %}
							<h2><p class="n1"><a style="color:white; text-decoration:none" href="{% url 'accounts:signup' %}">회원가입</a></p></h2>
							<h2><p class="n2"><a style="color:white; text-decoration:none" href="{% url 'accounts:login' %}">로그인</a></p></h2>
							{% endif %}
						</figcaption>			
					</figure>
				</div><!-- /container -->
		<script>
			// For Demo purposes only (show hover effect on mobile devices)
			[].slice.call( document.querySelectorAll('a[href="#"') ).forEach( function(el) {
				el.addEventListener( 'click', function(ev) { ev.preventDefault(); } );
			} );
		</script>
	</body>
</html>

Ohayo/movies/templates/movies/select.html
{% extends 'base.html' %}
{% block title %}취향 선택{% endblock %}
{% block css %}
{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'movies/stylesheets/select.css' %}" />
{% endblock %}
{% block body %}
    <div class="container">
      <ul class="ks-cboxtags">
        {% for keyword in keywords %}
        <li><input type="checkbox" id="{{ keyword.pk }}" value="{{ keyword.name }}"><label for="{{ keyword.pk }}">{{ keyword.name }}</label></li>
        {% endfor %}      
      </ul>
    
    </div>
{% endblock %}

Ohayo/movies/templates/movies/show_movies.html
{% extends 'base.html'%} 
{% block css %}
{% load static %}
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png">
    <!-- Plugin-CSS -->
    <link rel="stylesheet" href="{% static 'static/content/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'static/content/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'static/content/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'static/content/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'static/content/css/animate.css' %}">
    <!-- Main-Stylesheets -->
    <link rel="stylesheet" href="{% static 'static/content/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'static/content/style.css' %}">
    <link rel="stylesheet" href="{% static 'static/content/css/responsive.css' %}">
    <script src="{% static 'static/contetent/js/vendor/modernizr-2.8.3.min.js' %}"></script>
{% endblock %}
{% block body %}

<!--<a href="{% url 'accounts:logout' %}">로그아웃</a>-->
<a href="{% url 'movies:clear' %}">다시 선택</a>
<h1>{{user}}님이 여행하고 싶은 영화</h1>
<a href="{% url 'accounts:my_movie' %}">담은 영화</a></a>
    <h4>
        {% for movie in movies %}
        <i> <img src="{{movie.imageUrl}}" style="width: 150px; height: 150px;"></i> {% endfor %}</h4>
    <div id="app">
    <hr> {% for keyword in user_keywords %} {% if keyword.movies.all %}
    <h2> # {{keyword.name}}</h2>
    {% for key_movie in keyword.movies.all %}
    <button type="button" class="btn btn-white" data-toggle="modal" data-target="#exampleModal-{{key_movie.id}}" style="padding-top:0px; padding-bottom:0px;">
              <!--d block으로 나머지 공간에 마진을 만들고 ml-auto는 해당 구역 왼쪽에 그 마진을 할당하여 오른쪽으로 밀리게한다.-->
            <img src="{{ key_movie.imageUrl }}" style="width: 300px; height: 300px;">
    </button>
    {% include 'movies/show_detail.html' %}
    <p class="movieCd" style="display: none;">{{ key_movie.code }}</p>
    <p class="movieLike" style="display: none;">{{ key_movie.is_like }}</p>
    <p class="likeCount" style="display: none;">{{ key_movie.baged_users.all.count }}</p>
    <div v-for="movie in movies">
        <span v-if="movie.movieCd === '{{ key_movie.code }}'" v-text="movie.movieNm"></span>
        <i v-if="movie.movieCd === '{{ key_movie.code }}'" @click="likeMovies(movie, '{{ key_movie.pk }}')"
               :class="{fas: movie.is_like, far: !movie.is_like, 'fa-heart': true}"
               style="color:red">
       </i><br v-if="movie.movieCd === '{{ key_movie.code }}'">
       <span v-if="movie.movieCd === '{{ key_movie.code }}'"><span v-text="movie.likeCount"></span>명이 담아둔 영화</span>
    </div>
    <hr> {% endfor %} {% endif %} {% endfor %}</div>



{% endblock %} {% block script %}
<script>
    const app = new Vue({
        el: '#app',
        data: {
            movies : [],
        },
        mounted: function() {
            this.getMovies()
        
        },
        methods: {
            getMovies: function() {
                let movieList = document.querySelectorAll('.movieCd')
                let movieLike = document.querySelectorAll('.movieLike')
                let likeCount = document.querySelectorAll('.likeCount')
                console.log(movieList)
                console.log(movieLike)
                console.log(likeCount)
                movieList.forEach(function(movie) {
                    url=`http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key=dc062d6001f402446fc226e2399d815a&movieCd=${movie.innerText}`
                    axios.get(url)
                        .then(res => {
                            console.log(res)
                            app.$data.movies.push(res.data.movieInfoResult.movieInfo)
                            app.$data.movies = app.$data.movies.map((movie) => {
                                console.log(movieLike[0].innerText)
                                if (movieLike[0].innerText === 'True') {
                                    return {...movie, is_like: true, likeCount: likeCount[0].innerText}
                                } else {
                                    return {...movie, is_like: false, likeCount: likeCount[0].innerText}
                                }
                            })
                            console.log(app.$data.movies)
                            // console.log(res.data.movieInfoResult.movieInfo)
                            // this.movies.push(res.data.movieInfoResult.movieInfo)
                        })
                })
            },
            likeMovies: function(movie, moviePk) {
               axios.get(`/movies/${moviePk}/movie_like/`)
               .then(response => {
                   console.log(response)
                   movie.is_like = !movie.is_like
                   console.log(movie.likeCount)
                   if (movie.is_like) {
                       console.log(Number(movie.likeCount)+1)
                       movie.likeCount = Number(movie.likeCount)+1
                   } else {
                       console.log(Number(movie.likeCount)-1)
                       movie.likeCount = Number(movie.likeCount)-1
                   }
               })
               .catch(error => console.log(error))
           },
        }
    })
</script>
{% endblock %}